### ISSUE TITLE
spring 변경 / 객실 상세 내용 불러오기

### ISSUE THREAD

**Issue by Gahyeon19** [jooYeonIya/JJHOTEL#51]
## Description

- spring으로 변경하기

## Tasks

- [x] '객실 상세 내용 불러오기'를 spring으로 변경하기
- [ ] imageURL, room 정보 화면에 보여줘야함 (수정 필요)

**Comment by jooYeonIya** [comment]
image 미출력 문제는 images 폴더 위치 문제 (root 디렉토리로 위치했어야 했음) -> S3 사용 시 해결될 문제기 때문에 이슈 닫음
